audio_recv: doc updates.
JessicaTegner/teamtalk.py pull request #24
Opened 2024-11-11 15:20 UTC by blindelectron

# This pull request makes the folloing changes:

- **update code example for audio block usage.**
- **Add on_muxed_audio to event reference.**
- **Update whates new docs.**

2024-11-12 20:12 UTC, JessicaTegner commented
Hi @blindelectron  CI is failing. I fixed the error on the upstream branch, so if you could  rebase onto the up-to-date audio_recv branch, we can get this squared away

2024-11-13 20:36 UTC, JessicaTegner requested changes
@blindelectron

2024-11-13 20:36 UTC, JessicaTegner commented on docs/_static/csv/server_channel_n_file.csv
> +on_muxed_audio	teamtalk.MuxedAudioBlock	called when a muxed audio block is recieved, this is used to get audio from all users in the channel at once.
We are missing on_user_audio

2024-11-13 20:36 UTC, JessicaTegner commented on teamtalk/audio.py
> +            p = pyaudio.PyAudio
This example doesn't actually work...

2024-11-15 21:39 UTC, JessicaTegner commented
@blindelectron  merge conflicts

2024-11-20 03:02 UTC, blindelectron commented
Conflicts fixed and review issues resolved.

2024-11-22 21:53 UTC, merged